### ISSUE TITLE
Does it still work for this year?

### ISSUE THREAD

**Issue by momati-ninja** [SM2A/Digikala_BlackFriday_1400_Bot#1]
I want to use it for this year does it work for this year promos?

**Comment by SM2A** [comment]
I don't know how Digikala is planned to place this year the promo code. 
If it is going to be like the way that was in 1400, yes it is going to work. If not, after the event is ended, you may like to checkout my github for this year's bot.

**Comment by momati-ninja** [comment]
okey thank you
